### PR TITLE
[ADDED] "Exit" confirmation modal dialog

### LINKED ISSUE #4: "Exit" confirmation modal dialog
To prevent users from accidentally clicking the "Exit" button, we could add a confirmation modal that will appear after the button is clicked. That modal will ask the user if they really want to exit or not. This can be built into `index.html` following the same structure as other modals.

**Hint**:
This will require modifying the modals in `index.html`, and the exit trigger in `renderer.js`.

### PR DESCRIPTION
**Pull request by jihed-Sh**
To prevent users from accidentally clicking the "Exit" button, we  added a confirmation modal that will appear after the button is clicked. That modal will ask the user if they really want to exit or not. 
a further enhancement will be in my opinion , that in case the file is saved , the dialog wont show up else if it is not saved a dialog will show with (Save,Discard,Cancel) , that's  only an idea .
ps: i loved your project :))

### CODE REVIEW

**Comment by LyubomirT** [comment]
Thank you for your Pull Request! I'll run the code when I'm back home, your support is much appreciated! :D

**Comment by LyubomirT** [comment]
Seems to be working well, good work!

If it's okay with you, could you please integrate the additional suggestion you proposed? I assume it's related to the commented functions in the updated `main.js`.

**Comment by LyubomirT** [comment]
Okay! Thank you for the commit, I'm going to fork your version to test things out. I'll let you know how it works out.

**Comment by jihed-Sh** [comment]
Hello , is there any problems related to the task? is it working fine?

**Comment by LyubomirT** [comment]
> Hello , is there any problems related to the task? is it working fine?

Yes, I just didn't really have the time to test things out because of family-related issues and setting up a new laptop.

**Comment by LyubomirT** [comment]
Seems like it still shows the popup even though the file is saved, please fix it and the Pull Request will become merge-able right after that. :)

**Comment by jihed-Sh** [comment]
Hello my friend, i fixed the error you mentioned , it should work fine now ,can you please test it and let me know if something is not working ? have a great day :) !

**Comment by LyubomirT** [comment]
Sure, just a moment. Sorry for such a long discussion, I hope I'm not too annoying.

Anyways, I'm going to test it when it's morning (right now it's 2 AM), I'll let you know how it works out. Stay safe out there :D

**Comment by jihed-Sh** [comment]
No , not at all , thank you for being so understanding and patient with me . I honestly appreciate it .

**Comment by LyubomirT** [comment]
LGTM, it appears to be working! Thank you for your time @jihed-Sh, your help is truly appreciated. I'm merging the Pull Request right away.

**Pull request merged**
